apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.app_name }}
  namespace: {{ .Values.namespace }}
  annotations: 
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: {{ .Values.app_name }}-srv
          servicePort: 80
        path: /
