apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.app_name }}-srv
    namespace: {{ .Values.namespace }}
spec:
    selector:
        app: {{ .Values.app_name }}_npm
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
